version: "3.9"

networks:
  havadash_net:

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: havadash_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: havadashdb
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - havadash_postgres_data:/var/lib/postgresql/data
    networks:
      - havadash_net

  # Mosquitto MQTT broker
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: havadash_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - havadash_mosquitto_data:/mosquitto/data
      - havadash_mosquitto_log:/mosquitto/log
    networks:
      - havadash_net

  # Redis
  redis:
    image: redis:7-alpine
    container_name: havadash_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - havadash_redis_data:/data
    networks:
      - havadash_net

  # Redis Insight
  redis-ui:
    image: redis/redisinsight:latest
    container_name: havadash_redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"        # Host:Container port mapping
    volumes:
      - havadash_redisinsight:/data # Kalıcı veri için volume
    networks:
      - havadash_net

volumes:
  havadash_postgres_data:
  havadash_mosquitto_data:
  havadash_mosquitto_log:
  havadash_redis_data:
  havadash_redisinsight:
