openapi: 3.0.0
info:
  title: Title ...
  description: A basic API for ..., documented with OpenAPI and YAML.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server
tags:
  - name: Auth
    description: Authentication and authorization endpoints
  - name: Users
    description: User management endpoints
paths:
  /auth/login:
    post:
      summary: Log in a user
      tags:
        - Auth
      description: Authenticates a user and returns an authentication token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginRequest'
            examples:
              withPassword:
                summary: Login with password
                value:
                  email: admin@havadash.com
                  password: Admin1234*
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginResponse'
              examples:
                withPassword:
                  summary: Login with password
                  value:
                    status: success
                    statusCode: 200
                    message: Login successful
                    data:
                      userId: 123
                      email: admin@havadash.com
                      username: Admin
                      token: eyJhbGciOiJIUzI1NiIs....
                      expiresIn: 3600
        409:
          description: Unauthorized. Invalid email or password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 409
                message: Mevcutta şifre bulunmaktadır.
                data: null
        401:
          description: Unauthorized. Invalid email or password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 401
                message: Unauthorized. Invalid email or password.
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: Internal server error.
                data: null
  /auth/logout:
    post:
      summary: Log out
      tags:
        - Auth
      description: Logs out a user and invalidates their authentication token.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/logoutRequest'
            example:
              userId: 1
              refreshToken: ey7sd...
      responses:
        200:
          description: User logged out
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logoutResponse'
              example:
                status: success
                statusCode: 200
                message: User session ended.
                data:
                  result: true
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 400
                message: Unauthorized post_logout_redirect_uri
                data: null
        409:
          description: Mismatch refresh token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 409
                message: Refresh token mismatch.
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: Internal server error.
                data: null
  /users:
    get:
      tags:
        - Users
      summary: Get users with optional includes, field selection, filters, sorting and pagination
      parameters:
        - name: includes
          in: query
          description: Comma-seperated list of related resources to include
          schemas:
            type: string
        - name: fields[users]
          in: query
          description: Comma-seperated list of fields to return from user
          schemas:
            type: string
        - name: filter[users.roleCode]
          in: query
          description: Filter users by role code
          schemas:
            type: integer
        - name: sort[users.username]
          in: query
          description: Sort users by username
          schema:
            type: string
            enum: [asc, desc]
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/usersResponse'
        400:
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 400
                message: Invalid request parameters
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: An unexpected error occurred on the server
                data: null
    post:
      tags:
        - Users
      summary: Creates a new user
      description: Based on the information provided, it creates a new user record.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userCreateRequest'
      responses:
        201:
          description: The user was successfully created. It returns the created user object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userCreateResponse'
        400:
          description: Invalid request data. The sent data contains fields that are missing or in the wrong format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 400
                message: Invalid request data. The sent data contains fields that are missing or in the wrong format.
                data: null
        409:
          description: The user already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 409
                message: The user already exists.
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: An unexpected error occurred on the server
                data: null
  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The ID of the user to be processed
        schema:
          type: integer
    get:
      tags:
        - Users
      summary: Retrieves a single user by ID
      description: Retrieves the details of the user with the specified ID. Data associated with the `include` query parameter can also be retrieved.
      parameters:
        - name: include
          in: query
          required: false
          description: Comma-seperated list of related resources to include
          schemas:
            type: string
      responses:
        200:
          description: The user was successfully located and returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 404
                message: User not found.
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: An unexpected error occurred on the server
                data: null
    patch:
      tags:
        - Users
      summary: Updates an existing user
      description: Updates one or more fields of the user with the specified ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userUpdateRequest'
      responses:
        200:
          description: The user has been successfully updated. It will return the user's current version.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userUpdateResponse'
        400:
          description: Invalid request data. The sent data contains fields that are missing or in the wrong format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 400
                message: Invalid request data. The sent data contains fields that are missing or in the wrong format.
                data: null
        404:
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 404
                message: User not found.
                data: null
        409:
          description: The user already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 409
                message: The update data conflicts with another user.
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: An unexpected error occurred on the server
                data: null
    delete:
      tags:
        - Users
      summary: Deletes an existing user
      description: Permanently deletes the user with the specified ID from the database.
      responses:
        204:
          description: The user was successfully deleted. The response body is empty.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseResponse'
        404:
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 404
                message: User not found.
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: An unexpected error occurred on the server
                data: null
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Enter the JWT required to access the API here.'
  schemas:
    baseResponse:
      type: object
      properties:
        status:
          type: string
          description: The status of the API call (e.g., success, error).
        statusCode:
          type: integer
          description: HTTP status code.
        message:
          type: string
          description: Explanation of the transaction.
        data:
          type: object
          description: The main data returned by the response. The schema varies depending on the API endpoint.
    baseError:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: null
    base:
      type: object
      properties:
        id:
          type: integer
        status:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        createdBy:
          type: integer
        updatedBy:
          type: integer
    prmBase:
      type: object
      properties:
        code:
          type: string
        valueType:
          type: integer
          example: 1
        value:
          type: string
        description:
          type: string
        isActive:
          type: boolean
        order:
          type: integer
    loginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: The user's email address.
          pattern: ^[a-zA-Z0-9._]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$
        password:
          type: string
          format: password
          description: The user's password.
          minLength: 8
    loginResponse:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                userId:
                  type: integer
                email:
                  type: string
                username:
                  type: string
                token:
                  type: string
                expiresIn:
                  type: integer
    logoutRequest:
      type: object
      required:
        - userId
        - refreshToken
      properties:
        userId:
          type: integer
          description: The unique ID of the user.
        refreshToken:
          type: string
          description: The refresh token obtained from the login response.
    logoutResponse:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                result:
                  type: boolean
                  description: Indicates whether the logout was successful.
    usersResponse:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                products:
                  type: array
                  items:
                    $ref: '#/components/schemas/user'
            meta:
              type: object
              properties:
                currentPage:
                  type: integer
                totalPages:
                  type: integer
                totalItems:
                  type: integer
                limit:
                  type: integer
    userCreateRequest:
      type: object
      required:
        - createdBy
        - email
        - username
        - password
        - roleCode
      properties:
        createdBy:
          type: integer
        email:
          type: string
        username:
          type: string
        password:
          type: string
        roleCode:
          type: integer
    userCreateResponse:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                product:
                  $ref: '#/components/schemas/user'
    userUpdateRequest:
      type: object
      required:
        - updatedBy
      properties:
        updatedBy:
          type: integer
        email:
          type: string
        username:
          type: string
        password:
          type: string
        roleCode:
          type: integer
    userUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                user:
                  $ref: '#/components/schemas/user'
    user:
      allOf:
        - $ref: '#/components/schemas/base'
        - type: object
          properties:
            email:
              type: string
            userName:
              type: string
            passwordHash:
              type: string
            roleCode:
              type: integer
            role:
              $ref: '#/components/schemas/prmBase'

security:
  - bearerAuth: []