# Port ayarları
listener 1883
allow_anonymous true

# Websocket (opsiyonel)
listener 9001
protocol websockets

# Log ve data dizinleri
persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
