const EXCLUDED_URLS = [
  "/api/auth/register",
  "/api/auth/login",
  "/api/auth/set-password",
  "/api/auth/refresh-token",
  "/api/auth/logout",
];

const RESPONSE_STATUS = {
    SUCCESS: 'success',
    ERROR: 'error',
};

const HEADERS = {
    AUTHORIZATION: 'authorization',
    RETRYCOUNT: "x-retry-count",
    CONTENT_TYPE: 'Content-Type',
    CONTENT_DISPOSITION: 'Content-Disposition',
};

const HTTP_STATUS = {
    // 200
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTHOTITATIVE_INFORMATION: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    // 400
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    TOO_MANY_REQUESTS: 429,
    // 500
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
};

const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    INVALID_TOKEN: 'INVALID_TOKEN',
    EXPIRED_TOKEN: 'EXPIRED_TOKEN',
    USER_NOT_FOUND: 'USER_NOT_FOUND_ERROR',
    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST_ERROR',
    CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND_ERROR',
    CUSTOMER_ALREADY_EXIST: 'CUSTOMER_ALREADY_EXIST_ERROR',
    DRONE_NOT_FOUND: 'DRONE_NOT_FOUND_ERROR',
    DRONE_ALREADY_EXIST: 'DRONE_ALREADY_EXIST_ERROR',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND_ERROR',
    ORDER_ALREADY_EXIST: 'ORDER_ALREADY_EXIST_ERROR',
    COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND_ERROR',
    COUNTRY_ALREADY_EXIST: 'COUNTRY_ALREADY_EXIST_ERROR',
    CITY_NOT_FOUND: 'CITY_NOT_FOUND_ERROR',
    CITY_ALREADY_EXIST: 'CITY_ALREADY_EXIST_ERROR',
    ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND_ERROR',
    FLIGHT_NOT_FOUND: 'FLIGHT_NOT_FOUND_ERROR',
    FLIGH_LOCATION_NOT_FOUND: 'FLIGH_LOCATION_NOT_FOUND_ERROR',
    TELEMETRY_DATA_NOT_FOUND: 'TELEMETRY_DATA_NOT_FOUND_ERROR',
    ALARM_DATA_NOT_FOUND: 'ALARM_DATA_NOT_FOUND_ERROR',
    DRONE_COMMAND_NOT_FOUND: 'DRONE_COMMAND_NOT_FOUND_ERROR',
    CUSTOMER_ADDRESS_MAP_NOT_FOUND: 'CUSTOMER_ADDRESS_MAP_NOT_FOUND_ERROR',
    PRM_NOT_FOUND: 'PRM_NOT_FOUND_ERROR',
};

const ERROR_MESSAGES = {
    VALIDATION_ERROR: 'Geçersiz veri gönderildi.',
    UNAUTHORIZED: 'Yetkisiz erişim.',
    FORBIDDEN: 'Bu işlemi yapma yetkiniz yok.',
    NOT_FOUND: 'İstenen kaynak bulunamadı.',
    CONFLICT: 'Zaten mevcut bir kayıt var.',
    INTERNAL_SERVER_ERROR: 'Sunucuda beklenmeyen bir hata oluştu.',
    BAD_REQUEST: 'İstek geçersiz.',
    TOO_MANY_REQUESTS: 'Çok fazla istek yapıldı. Lütfen sonra tekrar deneyin.',
    SERVICE_UNAVAILABLE: 'Servis geçici olarak kullanılamıyor.',
    TOKEN_NOT_FOUND: '[Auth] Authorization header içinde token bulunamadı.',
    INVALID_TOKEN: '[Auth] Token geçersiz.',
    EXPIRED_TOKEN: '[Auth] Token süresi dolmuş.',
    USER_ALREADY_EXIST: 'Kullanıcı zaten mevcut.',
    USER_NOT_FOUND: 'Kullanıcı bulunamadı.',
    CUSTOMER_ALREADY_EXIST: 'Müşteri zaten tanımlı',
    CUSTOMER_NOT_FOUND: 'Müşteri bulunamadı.',
    DRONE_ALREADY_EXIST: 'Drone zaten tanımlı',
    DRONE_NOT_FOUND: 'Drone bulunamadı.',
    ORDER_NOT_FOUND: 'Sipariş bulunamadı.',
    ORDER_ALREADY_EXIST: 'Sipariş zaten tanımlı',
    COUNTRY_NOT_FOUND: 'Ülke bulunamadı.',
    COUNTRY_ALREADY_EXIST: 'Ülke zaten tanımlı',
    CITY_NOT_FOUND: 'İl bulunamadı.',
    CITY_ALREADY_EXIST: 'İl zaten tanımlı',
    ADDRESS_NOT_FOUND: 'İl bulunamadı.',
    FLIGHT_NOT_FOUND: 'Uçuş bulunamadı.',
    FLIGH_LOCATION_NOT_FOUND: 'Uçuş konumu bulunamadı.',
    TELEMETRY_DATA_NOT_FOUND: 'Telemetri verisi bulunamadı.',
    ALARM_DATA_NOT_FOUND: 'Alarm verisi bulunamadı.',
    DRONE_COMMAND_NOT_FOUND: 'Drone komutu bulunamadı.',
    CUSTOMER_ADDRESS_MAP_NOT_FOUND: 'Müşteri-adres bağlantısı bulunamadı.',
    PRM_NOT_FOUND: 'PRM tablosu bulunamadı.',
};

const ERROR_STATUS = {
    VALIDATION_ERROR: 400,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    TOKEN_NOT_FOUND: 401,
    INVALID_TOKEN: 403,
    EXPIRED_TOKEN: 401,

    USER_NOT_FOUND: 404,
    USER_ALREADY_EXIST: 409,
    CUSTOMER_NOT_FOUND: 404,
    CUSTOMER_ALREADY_EXIST: 409,
    DRONE_NOT_FOUND: 404,
    DRONE_ALREADY_EXIST: 409,
    ORDER_NOT_FOUND: 404,
    ORDER_ALREADY_EXIST: 409,
    COUNTRY_NOT_FOUND: 404,
    COUNTRY_ALREADY_EXIST: 409,
    CITY_NOT_FOUND: 404,
    CITY_ALREADY_EXIST: 409,
    ADDRESS_NOT_FOUND: 404,
    FLIGHT_NOT_FOUND: 404,
    FLIGH_LOCATION_NOT_FOUND: 404,
    TELEMETRY_DATA_NOT_FOUND: 404,
    ALARM_DATA_NOT_FOUND: 404,
    DRONE_COMMAND_NOT_FOUND: 404,
    CUSTOMER_ADDRESS_MAP_NOT_FOUND: 404,
    PRM_NOT_FOUND: 404,
};

const MESSAGES = {
    USER_LOGIN_SUCCESS: 'Başarıyla giriş yapıldı.',
    LOGOUT_SUCCESS: 'Oturum sonlandırıldı.',

    USER_FETCHED_SUCCESS: 'Kullanıcı başarıyla getirildi.',
    USERS_FETCHED_SUCCESS: 'Kullanıcılar başarıyla getirildi.',
    USER_CREATED_SUCCESS: 'Kullanıcı başarıyla oluşturuldu.',
    USER_UPDATED_SUCCESS: 'Kullanıcı başarıyla güncellendi.',
    USER_DELETED_SUCCESS: 'Kullanıcı başarıyla silindi.',

    CUSTOMER_FETCHED_SUCCESS: 'Müşteri başarıyla getirildi.',
    CUSTOMERS_FETCHED_SUCCESS: 'Müşteriler başarıyla getirildi.',
    CUSTOMER_CREATED_SUCCESS: 'Müşteri başarıyla oluşturuldu.',
    CUSTOMER_UPDATED_SUCCESS: 'Müşteri başarıyla güncellendi.',
    CUSTOMER_DELETED_SUCCESS: 'Müşteri başarıyla silindi.',

    DRONE_FETCHED_SUCCESS: 'Drone başarıyla getirildi.',
    DRONES_FETCHED_SUCCESS: 'Drone listesi başarıyla getirildi.',
    DRONE_CREATED_SUCCESS: 'Drone başarıyla oluşturuldu.',
    DRONE_UPDATED_SUCCESS: 'Drone başarıyla güncellendi.',
    DRONE_DELETED_SUCCESS: 'Drone başarıyla silindi.',

    ORDER_FETCHED_SUCCESS: 'Sipariş başarıyla getirildi.',
    ORDERS_FETCHED_SUCCESS: 'Sipariş listesi başarıyla getirildi.',
    ORDER_CREATED_SUCCESS: 'Sipariş başarıyla oluşturuldu.',
    ORDER_UPDATED_SUCCESS: 'Sipariş başarıyla güncellendi.',
    ORDER_DELETED_SUCCESS: 'Sipariş başarıyla silindi.',

    COUNTRY_FETCHED_SUCCESS: 'Ülke başarıyla getirildi.',
    COUNTRIES_FETCHED_SUCCESS: 'Ülke listesi başarıyla getirildi.',
    COUNTRY_CREATED_SUCCESS: 'Ülke başarıyla oluşturuldu.',
    COUNTRY_UPDATED_SUCCESS: 'Ülke başarıyla güncellendi.',
    COUNTRY_DELETED_SUCCESS: 'Ülke başarıyla silindi.',

    CITY_FETCHED_SUCCESS: 'İl başarıyla getirildi.',
    CITIES_FETCHED_SUCCESS: 'İl listesi başarıyla getirildi.',
    CITY_CREATED_SUCCESS: 'İl başarıyla oluşturuldu.',
    CITY_UPDATED_SUCCESS: 'İl başarıyla güncellendi.',
    CITY_DELETED_SUCCESS: 'İl başarıyla silindi.',

    ADDRESS_FETCHED_SUCCESS: 'Adres başarıyla getirildi.',
    ADDRESSES_FETCHED_SUCCESS: 'Adres listesi başarıyla getirildi.',
    ADDRESS_CREATED_SUCCESS: 'Adres başarıyla oluşturuldu.',
    ADDRESS_UPDATED_SUCCESS: 'Adres başarıyla güncellendi.',
    ADDRESS_DELETED_SUCCESS: 'Adres başarıyla silindi.',

    FLIGHT_FETCHED_SUCCESS: 'Uçuş başarıyla getirildi.',
    FLIGHTS_FETCHED_SUCCESS: 'Uçuş listesi başarıyla getirildi.',
    FLIGHT_CREATED_SUCCESS: 'Uçuş başarıyla oluşturuldu.',
    FLIGHT_UPDATED_SUCCESS: 'Uçuş başarıyla güncellendi.',
    FLIGHT_DELETED_SUCCESS: 'Uçuş başarıyla silindi.',

    FLIGHT_LOCATION_FETCHED_SUCCESS: 'Uçuş konum başarıyla getirildi.',
    FLIGHT_LOCATIONS_FETCHED_SUCCESS: 'Uçuş konum listesi başarıyla getirildi.',
    FLIGHT_LOCATION_CREATED_SUCCESS: 'Uçuş konum başarıyla oluşturuldu.',
    FLIGHT_LOCATION_UPDATED_SUCCESS: 'Uçuş konum başarıyla güncellendi.',
    FLIGHT_LOCATION_DELETED_SUCCESS: 'Uçuş konum başarıyla silindi.',

    TELEMETRY_DATA_FETCHED_SUCCESS: 'Telemetri verisi başarıyla getirildi.',
    TELEMETRY_DATA_LIST_FETCHED_SUCCESS: 'Telemetri veri listesi başarıyla getirildi.',
    TELEMETRY_DATA_CREATED_SUCCESS: 'Telemetri verisi başarıyla oluşturuldu.',
    TELEMETRY_DATA_UPDATED_SUCCESS: 'Telemetri verisi başarıyla güncellendi.',
    TELEMETRY_DATA_DELETED_SUCCESS: 'Telemetri verisi başarıyla silindi.',

    ALARM_DATA_FETCHED_SUCCESS: 'Alarm verisi başarıyla getirildi.',
    ALARM_DATA_LIST_FETCHED_SUCCESS: 'Alarm veri listesi başarıyla getirildi.',
    ALARM_DATA_CREATED_SUCCESS: 'Alarm verisi başarıyla oluşturuldu.',
    ALARM_DATA_UPDATED_SUCCESS: 'Alarm verisi başarıyla güncellendi.',
    ALARM_DATA_DELETED_SUCCESS: 'Alarm verisi başarıyla silindi.',

    DRONE_COMMAND_FETCHED_SUCCESS: 'Drone komutu başarıyla getirildi.',
    DRONE_COMMANDS_FETCHED_SUCCESS: 'Drone komut listesi başarıyla getirildi.',
    DRONE_COMMAND_CREATED_SUCCESS: 'Drone komutu başarıyla oluşturuldu.',
    DRONE_COMMAND_UPDATED_SUCCESS: 'Drone komutu başarıyla güncellendi.',
    DRONE_COMMAND_DELETED_SUCCESS: 'Drone komutu başarıyla silindi.',

    CUSTOMER_ADDRESS_MAP_FETCHED_SUCCESS: 'Müşteri-adres bağlantısı başarıyla getirildi.',
    CUSTOMER_ADDRESS_MAPS_FETCHED_SUCCESS: 'Müşteri-adres bağlantı listesi başarıyla getirildi.',
    CUSTOMER_ADDRESS_MAP_CREATED_SUCCESS: 'Müşteri-adres bağlantısı başarıyla oluşturuldu.',
    CUSTOMER_ADDRESS_MAP_UPDATED_SUCCESS: 'Müşteri-adres bağlantısı başarıyla güncellendi.',
    CUSTOMER_ADDRESS_MAP_DELETED_SUCCESS: 'Müşteri-adres bağlantısı başarıyla silindi.',

    PRM_FETCHED_SUCCESS: 'Prm tablosu başarıyla getirildi.',
    PRMS_FETCHED_SUCCESS: 'Prm tablo listesi başarıyla getirildi.',
    PRM_CREATED_SUCCESS: 'Prm tablosu başarıyla oluşturuldu.',
    PRM_UPDATED_SUCCESS: 'Prm tablosu başarıyla güncellendi.',
    PRM_DELETED_SUCCESS: 'Prm tablosu başarıyla silindi.',
};


export { 
  EXCLUDED_URLS,
  RESPONSE_STATUS,
  HEADERS,
  HTTP_STATUS,
  ERROR_CODES,
  ERROR_MESSAGES,
  ERROR_STATUS,
  MESSAGES
};